### ISSUE TITLE
Add more info to the notification email

### ISSUE THREAD

**Issue by seanrmurphy** [telefonicaid/fiware-health#112]
It would be good if the notification email sent to the list pertaining to that node included the following info:
- a link to the fi-health page which we could just click on
- the results of the tests so we could see the test results from the email and not just get a notification that there has been a change

I guess this is pretty obvious, so you prob have it on the todo list in any case...this is just to maybe push it up the prio list ;-)

**Comment by flopezag** [comment]
A ticket was created to resolve this issue in Sprint 5.1.2

https://jira.fiware.org/browse/OPS-623

**Comment by pratid** [comment]
Next release of FIHealth Sanity Checks will include this feature
