### ISSUE TITLE
external_network_name changed for Stockholm

### ISSUE THREAD

**Issue by rolelv** [telefonicaid/fiware-health#12]
New external_network_name = "public-ext-net-01"
(Old external_network_name = "XIFIpublicACREO")

**Comment by flopezag** [comment]
We create a PR #13 in order to resolve this issue. Next day the execution of the Validation Test will reflect this change.

**Comment by flopezag** [comment]
Please, if you consider that the issue was resolved, close it.

**Comment by rolelv** [comment]
Thanks for heads up.
