### ISSUE TITLE
Neuropublic external network name 

### ISSUE THREAD

**Issue by ghost** [telefonicaid/fiware-health#18]
Neuropublic external network name has been changed to public-ext-net-01 according to jira ticket NODEM-194 instructions. Please change accordingly.

**Comment by flopezag** [comment]
Just to confirm, you are talking about PiraeusN?

**Comment by ghost** [comment]
Correct fernando, sorry about that. PiraeusN is the correct name.

Fernando López Aguilar notifications@github.com , 20/3/2015 1:02 PM:

Just to confirm, you are talking about PiraeusN? 
—
Reply to this email directly or view it on GitHub. 

Disclaimer
NeuroPublic does not accept any legal responsibility, nor endorses any information contained in this message, 
which represents solely the author. Also, since this message has been transmitted over an insecure public network, 
NeuroPublic does not accept any responsibility for the accuracy or completeness of the message. 
This e-mail is private and confidential. If you are not the intended recipient, send us back the 
original message at: info@neuropublic.gr and delete the copies from your system. You are notified that copying the message, 
re-transmitting it, disclosing its contents or using it in any way is strictly prohibited.

H NeuroPublic δεν έχει καμία νομική ευθύνη, ούτε αποδέχεται οποιαδήποτε πληροφορία που περιέχεται στο παρόν μήνυμα, 
η οποία εκφράζει αποκλειστικά και μόνο το συγγραφέα. Επίσης, επειδή το παρόν μήνυμα διαβιβάστηκε μέσω μη ασφαλούς δημοσίου δικτύου, 
η NeuroPublic δεν έχει, ούτε αποδέχεται ουδεμία ευθύνη για την ακρίβεια ή πληρότητα του μηνύματος.
Το παρόν μήνυμα μέσω ηλεκτρονικού ταχυδρομείου (e-mail) είναι προσωπικό και εμπιστευτικό. Εάν δεν είστε ο σωστός παραλήπτης, 
παρακαλούμε να επιστρέψετε το αρχικό μήνυμα στη διεύθυνση info@neuropublic.gr και να διαγράψετε τα αντίγραφα από το σύστημά σας. 
Σας γνωστοποιούμε ότι η αντιγραφή του μηνύματος, η αναμετάδοσή του, η αποκάλυψη των περιεχομένων του 
ή η καθ' οιονδήποτε τρόπο χρήση του απαγορεύεται αυστηρώς.

**Comment by flopezag** [comment]
Might you check the issue and close it if it is resolved, thank you.

**Comment by ghost** [comment]
Done
