### ISSUE TITLE
Zurich name change (again)

### ISSUE THREAD

**Issue by seanrmurphy** [telefonicaid/fiware-health#20]
The Zurich public network name has been changed again to public-ext-net-01 according to jira ticket NODEM-194 instructions. (We had the same issue as Theofanis that we took the name agreed in the minutes of the Prague meeting for the previous issue, but this is not consistent with what we now see in the jira ticket).

Can you update please?

**Comment by flopezag** [comment]
It should be resolved with the PR #23, please consider to close the issue if you consider that it was resolved.

**Comment by seanrmurphy** [comment]
Yep - worked fine this morning - thanks.
