### ISSUE TITLE
PiraeusU Node - external network name changed

### ISSUE THREAD

**Issue by dgkelaidonis** [telefonicaid/fiware-health#21]
We have observed some differences between the results of the centralized sanity tests and the manual tests (through the cloud portal). 
- In particular, (maybe perchance) when we updated our floating nets to public-ext-net-01 , federation-ext-net-01 (instead public-ext-net-1 and federation-ext-net-1, respectively), after a NODEM jira request, we observed that the public/centralized sanity tests detects as error for out node the allocation of floating IPs ( ‘Sanity Test Output’ Error: FloatingIpPoolNotFound: Floating ip pool not found. (HTTP 404) (Request-ID: req-ffb39e9a-2679-44e6-9306-5f5165cef8ae) ).
- However, by performing manual testing everything works properly.
- Could you please check if the Sanity Test Suite for PiraeusU nod, needs any update after the floating networks name update? In the NODEM Jira Ticket, there was a comment that the network names are case sensitive. So potentially need somewhere in the scripts an update. 
  Apologies in advance if I have understood something wrong! 

Best Regards,
Dimitris Kelaidonis, on behalf of PiraeusU node

**Comment by flopezag** [comment]
It should be resolved with the PR #23, please consider to close the issue if you consider that it was resolved.

**Comment by dgkelaidonis** [comment]
Everything is ok now! The floating network is detected now.
Thank you!

**Comment by jacolex** [comment]
Please check Poznan node whether network names in scripts are updated to public-ext-net-01 and federation-ext-net-01
