### ISSUE TITLE
Add Zurich2 region

### ISSUE THREAD

**Issue by brunograz** [telefonicaid/fiware-health#227]
Please add Zurich2 region.
We have object-storage service but it shouldn't be included in the sanity check yet as there is an issue with keystone and the cloud portal for this service. We will create another issue to enable it as soon as this is fixed.

The public network name remains the same - public-ext-net-01.

**Comment by flopezag** [comment]
Could you provide me the name of the shared network? It is the same?

**Comment by brunograz** [comment]
It's the same as the other region - node-int-net-01.

**Comment by flopezag** [comment]
The PR is merged the deployment of the following release of the FI-Health tool will include the new region.
