### ISSUE TITLE
Network renamed in Budapest node

### ISSUE THREAD

**Issue by slaki** [telefonicaid/fiware-health#26]
Dear Fernando,

we renamed our networks. Please change the sanity check configuration. The names was changed to:

mdvpnInternal    ->    node-int-net-02
publicInternal    ->    node-int-net-01
mdvpnRange        ->    federation-ext-net-01
publicRange        ->    public-ext-net-01

Thanks,
Gergő

**Comment by flopezag** [comment]
It should be resolved with the PR #28, please consider to close the issue if you consider that it was resolved.
