### ISSUE TITLE
Lannion2 is missing

### ISSUE THREAD

**Issue by rkerherve** [telefonicaid/fiware-health#53]
Lannion2 is on air since monday 27/04. Could you please add it to the nodes that are tests every morning?

BR
rkerherve

**Comment by flopezag** [comment]
Hi, Riwal,

We are assuming that the name of the network is the same that you had in Lannion instance. If it is incorrect let me know.

**Comment by rkerherve** [comment]
I answered you by skype... i think this is ok

Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Fernando López Aguilar notifications@github.com
Date : 30/04/2015 18:54 (GMT+01:00)
À : telefonicaid/fiware-health fiware-health@noreply.github.com
Cc : Riwal KERHERVE rkerherve@images-et-reseaux.com
Objet : Re: [fiware-health] Lannion2 is missing (#53)

Hi, Riwal,

We are assuming that the name of the network is the same that you had in Lannion instance. If it is incorrect let me know.

**Comment by rkerherve** [comment]
Hi Fernando,
Just to be sure the answered passed, the name of the external network is:public-ext-net-01

**Comment by flopezag** [comment]
Yes, it is sure, it was merged into develop today. But we are following internal QA process previously to make migrations to master. When we check all new functionalities without any problem in develop we migrate to master.

See #56

**Comment by rkerherve** [comment]
Fernando,

So I think, it is best to remove from the sanity check the node "Lannion", as we remove it already from the infographic.

BR
Riwal

**Comment by rkerherve** [comment]
Lannion2 is now on the infographic, we can close the issue.

BR
Riwal
