### ISSUE TITLE
Add timestamp on error reports to help with debugging in logs

### ISSUE THREAD

**Issue by seanrmurphy** [telefonicaid/fiware-health#57]
It would be good if the error reports had specific times associated with them - it would be good if you could log time at the start of the test as well as the time when you conclude the test fails. This info should be printed in the error log. 

It would really help debugging - right now, the only time reference we have is the time at the top of http://fi-health.lab.fi-ware.eu/RegionSanityCheck/ which I guess is the time when all the tests end.

Thanks,
Seán.

**Comment by flopezag** [comment]
We are making several changes in the architecture of the Health and in the next release to master we can have more information about the time in which we execute them.

**Comment by flopezag** [comment]
Dear Seán,

When you talk about this functionality, do you mean to add the time per each executed test?

**Comment by seanrmurphy** [comment]
Hi Fernando,

Basically yes...

Anything that helps to make it easier to fix problems that are flagged in the sanity checks would be good. Right now, we have the issue that the only timestamp we have from the sanity checks is the time on at the top of the page which I assume is the time that all tests finish. It is a bit difficult to estimate exactly when a failed test might have taken place.

Basically, it would be good if the testing framework logs the start time and end time of each test and this is printed in any error reports - we could then use this as a reference time to look in our logs.

**Comment by flopezag** [comment]
We have several tickets created to produce this information:
- https://jira.fiware.org/browse/OPS-547
- https://jira.fiware.org/browse/OPS-624

Based on the result of the OPS-624 we provide new issues for Sprint 5.1.3

**Comment by pratid** [comment]
Next release of FIHealth Sanity Checks will include this feature
