### ISSUE TITLE
Budapest2 is missing

### ISSUE THREAD

**Issue by slaki** [telefonicaid/fiware-health#65]
Dear All,

"Budapest2" is up and running since monday, based on IceHouse. Could you please add it to the sanity check?

We use the same network names as in the "Budapest" region.

Thank you in advance,
Best,
Sandor

**Comment by flopezag** [comment]
Dear Sandor,

In order to introduce the new region I need to know if this new one has neutron and swift (object storage)?

**Comment by slaki** [comment]
Dear Fernando,

Yes, both neutron and swift have been installed, and available.

Best,
Sandor
2015.05.07. 10:25 ezt írta ("Fernando López Aguilar" <
notifications@github.com>):

**Comment by flopezag** [comment]
Perfect

**Comment by slaki** [comment]
Today we do not see Budapest2 in the sanity check page...

**Comment by flopezag** [comment]
Dear Sandor,

We just make a hotfix to master (#78) in order that the Budapest2 region can be shown in the next execution of the test.
