### ISSUE TITLE
Please add Berlin2

### ISSUE THREAD

**Issue by tgu-git** [telefonicaid/fiware-health#75]
Please add Berlin2 for sanity check. Berlin can be removed, because it should not be used by the users anymore.

**Comment by flopezag** [comment]
Dear Berlin administrator,

I need to know some things about the new Berlin node:
- Are you using Object Storage in that node?
- The name of the network is the same that you had in Berlin1? I mean public-ext-net-01?

**Comment by tgu-git** [comment]
The name of the external network is public-ext-net-01.
Yes we are providing object storage.
