### ISSUE TITLE
Zurich external network name

### ISSUE THREAD

**Issue by brunograz** [telefonicaid/fiware-health#9]
We see we have an error in one of the tests, most likely because the centralized test assumes that the name of our external network is net04_ext instead of public-ext-net-1. If you could change this I think we might be able to pass all test tomorrow. 

Thanks,
Bruno.

**Comment by flopezag** [comment]
Dear Bruno, it is not the first time that we change the network in Zürich, could you asure me that it is the final value of the network?

**Comment by flopezag** [comment]
We create a specific issue to resolve it: #10

**Comment by flopezag** [comment]
This issue was merged, you can close the issue when you check it.
